### ISSUE TITLE
Updating open_webrtc_browser() in Compat.rb

### ISSUE THREAD

**Issue by hkerma** [rapid7/rex-core#9]
Hi,
I opened an [issue](https://github.com/rapid7/metasploit-framework/issues/12113) for msf because I was having troubles with opening documentation.
Finally, I found out that `open_browser()` function were using `'xdg-open'` and `'sensible-browser'` first (which I think is a good thing) but `open_webrtc_browser()` uses `'google-chrome'` first.

I've found out two solutions :
- update `open_webrtc_browser()` function by providing `'xdg-open'` and `'sensible-browser'` first (but I'm not sure, as I don't really understand the purpose of this function compared to `open_browser()`).
- or, update msf's document_generator.rb file, by replacing `open_webrtc_function()`with `open_browser()` in order to make it more usable (cf. [issue](https://github.com/rapid7/metasploit-framework/issues/12113)).

Could someone tell me what solution in your opinion, is the best ? I'll then make the modifications and make a pull request.

**Comment by hkerma** [comment]
Hi !
As I get no answer, I'll make a PR soon with 'open_webrtc_browser()' calling 'xdg-open' and 'sensible-browser' first !

**Comment by busterb** [comment]
Sounds great, thanks @hkerma
